server:  port: 5008
  
spring:
  application:
    name: API-GATEWAY  cloud:    gateway:       routes:         - id: USER-SERVICE           uri: lb://USER-SERVICE           predicates:             - Path=/api/v1/**            